### ISSUE TITLE
registration is working, login isnt.

### ISSUE THREAD

**Issue by engageintellect** [vercel/nextjs-mysql-auth-starter#13]
I cloned the repo and connected to a local mysql instance.

I am able to register an email/password (with data being updated in database), but when trying to login, I keep getting a 307 redirect back to the login page.

What am I missing?

TIA

**Comment by abtonc** [comment]
Probably, you did not specify the NEXTAUTH_SECRET env variable. Generate one from [HERE](https://generate-secret.vercel.app/32) and export it `export NEXTAUTH_SECRET={your_secret_here}` (or put it into a .env file). This is only required for the localhost development.

**Comment by steven-tey** [comment]
@abtonc's exactly right – thank you for weighing in! :)

**Comment by engageintellect** [comment]
> Probably, you did not specify the NEXTAUTH_SECRET env variable. Generate one from [HERE](https://generate-secret.vercel.app/32) and export it `export NEXTAUTH_SECRET={your_secret_here}` (or put it into a .env file). This is only required for the localhost development.

Thank you my friend! You saved the day. 👏👏👏

Much appreciated.
